// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tusach_model.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BookStatusType int32

const (
	BookStatusType_NONE        BookStatusType = 0
	BookStatusType_IN_PROGRESS BookStatusType = 1
	BookStatusType_COMPLETED   BookStatusType = 2
	BookStatusType_ERROR       BookStatusType = 3
	BookStatusType_ABORTED     BookStatusType = 4
)

var BookStatusType_name = map[int32]string{
	0: "NONE",
	1: "IN_PROGRESS",
	2: "COMPLETED",
	3: "ERROR",
	4: "ABORTED",
}
var BookStatusType_value = map[string]int32{
	"NONE":        0,
	"IN_PROGRESS": 1,
	"COMPLETED":   2,
	"ERROR":       3,
	"ABORTED":     4,
}

func (x BookStatusType) String() string {
	return proto.EnumName(BookStatusType_name, int32(x))
}
func (BookStatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_27b3cbeaeae12463, []int{0}
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Roles                string   `protobuf:"bytes,2,opt,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_27b3cbeaeae12463, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRoles() string {
	if m != nil {
		return m.Roles
	}
	return ""
}

type SystemInfo struct {
	SystemUpTime         *timestamp.Timestamp `protobuf:"bytes,1,opt,name=systemUpTime,proto3" json:"systemUpTime,omitempty"`
	BookLastUpdatedTime  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=bookLastUpdatedTime,proto3" json:"bookLastUpdatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SystemInfo) Reset()         { *m = SystemInfo{} }
func (m *SystemInfo) String() string { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()    {}
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_27b3cbeaeae12463, []int{1}
}
func (m *SystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfo.Unmarshal(m, b)
}
func (m *SystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfo.Marshal(b, m, deterministic)
}
func (dst *SystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo.Merge(dst, src)
}
func (m *SystemInfo) XXX_Size() int {
	return xxx_messageInfo_SystemInfo.Size(m)
}
func (m *SystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo proto.InternalMessageInfo

func (m *SystemInfo) GetSystemUpTime() *timestamp.Timestamp {
	if m != nil {
		return m.SystemUpTime
	}
	return nil
}

func (m *SystemInfo) GetBookLastUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.BookLastUpdatedTime
	}
	return nil
}

type Book struct {
	ID                   int32                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status               BookStatusType       `protobuf:"varint,2,opt,name=status,proto3,enum=model.BookStatusType" json:"status,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author               string               `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	CreatedBy            string               `protobuf:"bytes,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	BuildTimeSec         int32                `protobuf:"varint,7,opt,name=buildTimeSec,proto3" json:"buildTimeSec,omitempty"`
	StartPageUrl         string               `protobuf:"bytes,8,opt,name=startPageUrl,proto3" json:"startPageUrl,omitempty"`
	CurrentPageUrl       string               `protobuf:"bytes,9,opt,name=currentPageUrl,proto3" json:"currentPageUrl,omitempty"`
	CurrentPageNo        int32                `protobuf:"varint,10,opt,name=currentPageNo,proto3" json:"currentPageNo,omitempty"`
	MaxNumPages          int32                `protobuf:"varint,11,opt,name=maxNumPages,proto3" json:"maxNumPages,omitempty"`
	LastUpdatedTime      *timestamp.Timestamp `protobuf:"bytes,12,opt,name=lastUpdatedTime,proto3" json:"lastUpdatedTime,omitempty"`
	ErrorMsg             string               `protobuf:"bytes,13,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	EpubCreated          bool                 `protobuf:"varint,14,opt,name=epubCreated,proto3" json:"epubCreated,omitempty"`
	Deleted              bool                 `protobuf:"varint,15,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_27b3cbeaeae12463, []int{2}
}
func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (dst *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(dst, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Book) GetStatus() BookStatusType {
	if m != nil {
		return m.Status
	}
	return BookStatusType_NONE
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *Book) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Book) GetBuildTimeSec() int32 {
	if m != nil {
		return m.BuildTimeSec
	}
	return 0
}

func (m *Book) GetStartPageUrl() string {
	if m != nil {
		return m.StartPageUrl
	}
	return ""
}

func (m *Book) GetCurrentPageUrl() string {
	if m != nil {
		return m.CurrentPageUrl
	}
	return ""
}

func (m *Book) GetCurrentPageNo() int32 {
	if m != nil {
		return m.CurrentPageNo
	}
	return 0
}

func (m *Book) GetMaxNumPages() int32 {
	if m != nil {
		return m.MaxNumPages
	}
	return 0
}

func (m *Book) GetLastUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdatedTime
	}
	return nil
}

func (m *Book) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *Book) GetEpubCreated() bool {
	if m != nil {
		return m.EpubCreated
	}
	return false
}

func (m *Book) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type BookList struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	IsFullList           bool     `protobuf:"varint,2,opt,name=isFullList,proto3" json:"isFullList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookList) Reset()         { *m = BookList{} }
func (m *BookList) String() string { return proto.CompactTextString(m) }
func (*BookList) ProtoMessage()    {}
func (*BookList) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_27b3cbeaeae12463, []int{3}
}
func (m *BookList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookList.Unmarshal(m, b)
}
func (m *BookList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookList.Marshal(b, m, deterministic)
}
func (dst *BookList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookList.Merge(dst, src)
}
func (m *BookList) XXX_Size() int {
	return xxx_messageInfo_BookList.Size(m)
}
func (m *BookList) XXX_DiscardUnknown() {
	xxx_messageInfo_BookList.DiscardUnknown(m)
}

var xxx_messageInfo_BookList proto.InternalMessageInfo

func (m *BookList) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func (m *BookList) GetIsFullList() bool {
	if m != nil {
		return m.IsFullList
	}
	return false
}

type NewBookRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartPageUrl         string   `protobuf:"bytes,2,opt,name=startPageUrl,proto3" json:"startPageUrl,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	MaxNumPages          int32    `protobuf:"varint,4,opt,name=maxNumPages,proto3" json:"maxNumPages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBookRequest) Reset()         { *m = NewBookRequest{} }
func (m *NewBookRequest) String() string { return proto.CompactTextString(m) }
func (*NewBookRequest) ProtoMessage()    {}
func (*NewBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_27b3cbeaeae12463, []int{4}
}
func (m *NewBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBookRequest.Unmarshal(m, b)
}
func (m *NewBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBookRequest.Marshal(b, m, deterministic)
}
func (dst *NewBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBookRequest.Merge(dst, src)
}
func (m *NewBookRequest) XXX_Size() int {
	return xxx_messageInfo_NewBookRequest.Size(m)
}
func (m *NewBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewBookRequest proto.InternalMessageInfo

func (m *NewBookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewBookRequest) GetStartPageUrl() string {
	if m != nil {
		return m.StartPageUrl
	}
	return ""
}

func (m *NewBookRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *NewBookRequest) GetMaxNumPages() int32 {
	if m != nil {
		return m.MaxNumPages
	}
	return 0
}

type BookID struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookID) Reset()         { *m = BookID{} }
func (m *BookID) String() string { return proto.CompactTextString(m) }
func (*BookID) ProtoMessage()    {}
func (*BookID) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_27b3cbeaeae12463, []int{5}
}
func (m *BookID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookID.Unmarshal(m, b)
}
func (m *BookID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookID.Marshal(b, m, deterministic)
}
func (dst *BookID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookID.Merge(dst, src)
}
func (m *BookID) XXX_Size() int {
	return xxx_messageInfo_BookID.Size(m)
}
func (m *BookID) XXX_DiscardUnknown() {
	xxx_messageInfo_BookID.DiscardUnknown(m)
}

var xxx_messageInfo_BookID proto.InternalMessageInfo

func (m *BookID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Chapter struct {
	ChapterNo            int32    `protobuf:"varint,1,opt,name=chapterNo,proto3" json:"chapterNo,omitempty"`
	BookId               int32    `protobuf:"varint,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Html                 []byte   `protobuf:"bytes,4,opt,name=html,proto3" json:"html,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chapter) Reset()         { *m = Chapter{} }
func (m *Chapter) String() string { return proto.CompactTextString(m) }
func (*Chapter) ProtoMessage()    {}
func (*Chapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_27b3cbeaeae12463, []int{6}
}
func (m *Chapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chapter.Unmarshal(m, b)
}
func (m *Chapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chapter.Marshal(b, m, deterministic)
}
func (dst *Chapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chapter.Merge(dst, src)
}
func (m *Chapter) XXX_Size() int {
	return xxx_messageInfo_Chapter.Size(m)
}
func (m *Chapter) XXX_DiscardUnknown() {
	xxx_messageInfo_Chapter.DiscardUnknown(m)
}

var xxx_messageInfo_Chapter proto.InternalMessageInfo

func (m *Chapter) GetChapterNo() int32 {
	if m != nil {
		return m.ChapterNo
	}
	return 0
}

func (m *Chapter) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Chapter) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Chapter) GetHtml() []byte {
	if m != nil {
		return m.Html
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "model.User")
	proto.RegisterType((*SystemInfo)(nil), "model.SystemInfo")
	proto.RegisterType((*Book)(nil), "model.Book")
	proto.RegisterType((*BookList)(nil), "model.BookList")
	proto.RegisterType((*NewBookRequest)(nil), "model.NewBookRequest")
	proto.RegisterType((*BookID)(nil), "model.BookID")
	proto.RegisterType((*Chapter)(nil), "model.Chapter")
	proto.RegisterEnum("model.BookStatusType", BookStatusType_name, BookStatusType_value)
}

func init() { proto.RegisterFile("tusach_model.proto", fileDescriptor_tusach_model_27b3cbeaeae12463) }

var fileDescriptor_tusach_model_27b3cbeaeae12463 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0xfd, 0xa5, 0x4d, 0xfa, 0xe7, 0xa6, 0xeb, 0xaa, 0xfb, 0x03, 0x64, 0x4d, 0x08, 0x4a, 0x84,
	0xd0, 0x84, 0x44, 0x87, 0xc6, 0x2b, 0x42, 0x62, 0x6b, 0x41, 0x95, 0xba, 0x74, 0x72, 0xdb, 0xe7,
	0x29, 0x6d, 0xbc, 0x36, 0x5a, 0x32, 0x87, 0xd8, 0x11, 0xec, 0x9d, 0x4f, 0xc1, 0x3b, 0xdf, 0x13,
	0xf9, 0xa6, 0x5d, 0xd3, 0x32, 0xb4, 0x37, 0x9f, 0xe3, 0xe3, 0xfb, 0xf7, 0x18, 0x50, 0xe7, 0x2a,
	0x58, 0xac, 0xae, 0x12, 0x19, 0x8a, 0xb8, 0x97, 0x66, 0x52, 0x4b, 0x74, 0x08, 0x1c, 0xbd, 0x5c,
	0x4a, 0xb9, 0x8c, 0xc5, 0x09, 0x91, 0xf3, 0xfc, 0xfa, 0x44, 0x47, 0x89, 0x50, 0x3a, 0x48, 0xd2,
	0x42, 0xe7, 0xbd, 0x07, 0x7b, 0xa6, 0x44, 0x86, 0x08, 0xf6, 0x6d, 0x90, 0x08, 0x66, 0x75, 0xad,
	0xe3, 0x26, 0xa7, 0x33, 0x3e, 0x01, 0x27, 0x93, 0xb1, 0x50, 0xac, 0x42, 0x64, 0x01, 0xbc, 0x5f,
	0x16, 0xc0, 0xe4, 0x4e, 0x69, 0x91, 0x0c, 0x6f, 0xaf, 0x25, 0x7e, 0x82, 0x96, 0x22, 0x34, 0x4b,
	0xa7, 0xd1, 0x3a, 0x80, 0x7b, 0x7a, 0xd4, 0x2b, 0x12, 0xf7, 0x36, 0x89, 0x7b, 0xd3, 0x4d, 0x62,
	0xbe, 0xa3, 0xc7, 0x11, 0xfc, 0x3f, 0x97, 0xf2, 0x66, 0x14, 0x28, 0x3d, 0x4b, 0xc3, 0x40, 0x8b,
	0x90, 0xc2, 0x54, 0x1e, 0x0d, 0xf3, 0xd0, 0x33, 0xef, 0xb7, 0x0d, 0xf6, 0x99, 0x94, 0x37, 0xd8,
	0x86, 0xca, 0xb0, 0x4f, 0xc5, 0x38, 0xbc, 0x32, 0xec, 0xe3, 0x3b, 0xa8, 0x29, 0x1d, 0xe8, 0xbc,
	0x68, 0xa6, 0x7d, 0xfa, 0xb4, 0x57, 0x4c, 0xcb, 0x88, 0x27, 0x74, 0x31, 0xbd, 0x4b, 0x05, 0x5f,
	0x8b, 0x4c, 0xeb, 0x3a, 0xd2, 0xb1, 0x60, 0xd5, 0xa2, 0x75, 0x02, 0xf8, 0x0c, 0x6a, 0x41, 0xae,
	0x57, 0x32, 0x63, 0x36, 0xd1, 0x6b, 0x84, 0x1f, 0xc1, 0x5d, 0x64, 0xe2, 0xbe, 0x76, 0xe7, 0xd1,
	0xda, 0xcb, 0x72, 0x7c, 0x0e, 0xcd, 0x35, 0x3c, 0xbb, 0x63, 0x35, 0x0a, 0xbc, 0x25, 0xd0, 0x83,
	0xd6, 0x3c, 0x8f, 0x62, 0x92, 0x4e, 0xc4, 0x82, 0xd5, 0xa9, 0xa5, 0x1d, 0xce, 0x68, 0x94, 0x0e,
	0x32, 0x7d, 0x19, 0x2c, 0xc5, 0x2c, 0x8b, 0x59, 0x83, 0x82, 0xec, 0x70, 0xf8, 0x06, 0xda, 0x8b,
	0x3c, 0xcb, 0xc4, 0xed, 0xbd, 0xaa, 0x49, 0xaa, 0x3d, 0x16, 0x5f, 0xc3, 0x41, 0x89, 0xf1, 0x25,
	0x03, 0x4a, 0xb8, 0x4b, 0x62, 0x17, 0xdc, 0x24, 0xf8, 0xe1, 0xe7, 0x89, 0xc1, 0x8a, 0xb9, 0xa4,
	0x29, 0x53, 0xd8, 0x87, 0xc3, 0x78, 0x6f, 0xa7, 0xad, 0x47, 0xe7, 0xb2, 0xff, 0x04, 0x8f, 0xa0,
	0x21, 0xb2, 0x4c, 0x66, 0x17, 0x6a, 0xc9, 0x0e, 0xa8, 0xde, 0x7b, 0x6c, 0x6a, 0x10, 0x69, 0x3e,
	0x3f, 0x2f, 0x46, 0xc5, 0xda, 0x5d, 0xeb, 0xb8, 0xc1, 0xcb, 0x14, 0x32, 0xa8, 0x87, 0x22, 0x16,
	0xe6, 0xf6, 0x90, 0x6e, 0x37, 0xd0, 0xbb, 0x80, 0x86, 0xd9, 0xfc, 0x28, 0x52, 0x1a, 0x5f, 0x81,
	0x63, 0xac, 0xa4, 0x98, 0xd5, 0xad, 0x1e, 0xbb, 0xa7, 0x6e, 0xc9, 0x19, 0xbc, 0xb8, 0xc1, 0x17,
	0x00, 0x91, 0xfa, 0x92, 0xc7, 0xb1, 0x79, 0x40, 0x0e, 0x6a, 0xf0, 0x12, 0xe3, 0xfd, 0xb4, 0xa0,
	0xed, 0x8b, 0xef, 0xf4, 0x44, 0x7c, 0xcb, 0x85, 0xd2, 0x5b, 0x07, 0x59, 0x65, 0x07, 0xed, 0x6f,
	0xaa, 0xf2, 0xc0, 0xa6, 0xb6, 0x2e, 0xab, 0xee, 0xb8, 0x6c, 0x6f, 0xe6, 0xf6, 0x5f, 0x33, 0xf7,
	0x18, 0xd4, 0x4c, 0x09, 0xc3, 0xbe, 0xb1, 0x7f, 0x14, 0x6e, 0xec, 0x1f, 0x85, 0x5e, 0x04, 0xf5,
	0xf3, 0x55, 0x90, 0x6a, 0x91, 0x91, 0xdd, 0x8a, 0xa3, 0x2f, 0xd7, 0x8a, 0x2d, 0x61, 0x92, 0x9b,
	0x96, 0x87, 0x21, 0x95, 0xe6, 0xf0, 0x35, 0xfa, 0xc7, 0x87, 0x40, 0xb0, 0x57, 0x3a, 0x89, 0xa9,
	0x96, 0x16, 0xa7, 0xf3, 0x5b, 0x0e, 0xed, 0xdd, 0x4f, 0x85, 0x0d, 0xb0, 0xfd, 0xb1, 0x3f, 0xe8,
	0xfc, 0x87, 0x87, 0xe0, 0x0e, 0xfd, 0xab, 0x4b, 0x3e, 0xfe, 0xca, 0x07, 0x93, 0x49, 0xc7, 0xc2,
	0x03, 0x68, 0x9e, 0x8f, 0x2f, 0x2e, 0x47, 0x83, 0xe9, 0xa0, 0xdf, 0xa9, 0x60, 0x13, 0x9c, 0x01,
	0xe7, 0x63, 0xde, 0xa9, 0xa2, 0x0b, 0xf5, 0xcf, 0x67, 0x63, 0x6e, 0x78, 0x7b, 0x5e, 0x23, 0xaf,
	0x7c, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x05, 0xe1, 0x70, 0x50, 0xea, 0x04, 0x00, 0x00,
}
