// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tusach_model.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BookStatusType int32

const (
	BookStatusType_NONE        BookStatusType = 0
	BookStatusType_IN_PROGRESS BookStatusType = 1
	BookStatusType_COMPLETED   BookStatusType = 2
	BookStatusType_ERROR       BookStatusType = 3
	BookStatusType_ABORTED     BookStatusType = 4
)

var BookStatusType_name = map[int32]string{
	0: "NONE",
	1: "IN_PROGRESS",
	2: "COMPLETED",
	3: "ERROR",
	4: "ABORTED",
}
var BookStatusType_value = map[string]int32{
	"NONE":        0,
	"IN_PROGRESS": 1,
	"COMPLETED":   2,
	"ERROR":       3,
	"ABORTED":     4,
}

func (x BookStatusType) String() string {
	return proto.EnumName(BookStatusType_name, int32(x))
}
func (BookStatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_e737636721060213, []int{0}
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Roles                []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_e737636721060213, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type SystemInfo struct {
	SystemUpTime         int64    `protobuf:"varint,1,opt,name=systemUpTime,proto3" json:"systemUpTime,omitempty"`
	BookLastUpdatedTime  int64    `protobuf:"varint,2,opt,name=bookLastUpdatedTime,proto3" json:"bookLastUpdatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfo) Reset()         { *m = SystemInfo{} }
func (m *SystemInfo) String() string { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()    {}
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_e737636721060213, []int{1}
}
func (m *SystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfo.Unmarshal(m, b)
}
func (m *SystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfo.Marshal(b, m, deterministic)
}
func (dst *SystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo.Merge(dst, src)
}
func (m *SystemInfo) XXX_Size() int {
	return xxx_messageInfo_SystemInfo.Size(m)
}
func (m *SystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo proto.InternalMessageInfo

func (m *SystemInfo) GetSystemUpTime() int64 {
	if m != nil {
		return m.SystemUpTime
	}
	return 0
}

func (m *SystemInfo) GetBookLastUpdatedTime() int64 {
	if m != nil {
		return m.BookLastUpdatedTime
	}
	return 0
}

type Book struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               BookStatusType `protobuf:"varint,2,opt,name=status,proto3,enum=model.BookStatusType" json:"status,omitempty"`
	Title                string         `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author               string         `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	CreatedTime          int64          `protobuf:"varint,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	CreatedBy            string         `protobuf:"bytes,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	BuildTimeSec         int32          `protobuf:"varint,7,opt,name=buildTimeSec,proto3" json:"buildTimeSec,omitempty"`
	StartPageUrl         string         `protobuf:"bytes,8,opt,name=startPageUrl,proto3" json:"startPageUrl,omitempty"`
	CurrentPageUrl       string         `protobuf:"bytes,9,opt,name=currentPageUrl,proto3" json:"currentPageUrl,omitempty"`
	CurrentPageNo        int32          `protobuf:"varint,10,opt,name=currentPageNo,proto3" json:"currentPageNo,omitempty"`
	MaxNumPages          int32          `protobuf:"varint,11,opt,name=maxNumPages,proto3" json:"maxNumPages,omitempty"`
	LastUpdatedTime      int64          `protobuf:"varint,12,opt,name=lastUpdatedTime,proto3" json:"lastUpdatedTime,omitempty"`
	ErrorMsg             string         `protobuf:"bytes,13,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	EpubCreated          bool           `protobuf:"varint,14,opt,name=epubCreated,proto3" json:"epubCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_e737636721060213, []int{2}
}
func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (dst *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(dst, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetStatus() BookStatusType {
	if m != nil {
		return m.Status
	}
	return BookStatusType_NONE
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Book) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Book) GetBuildTimeSec() int32 {
	if m != nil {
		return m.BuildTimeSec
	}
	return 0
}

func (m *Book) GetStartPageUrl() string {
	if m != nil {
		return m.StartPageUrl
	}
	return ""
}

func (m *Book) GetCurrentPageUrl() string {
	if m != nil {
		return m.CurrentPageUrl
	}
	return ""
}

func (m *Book) GetCurrentPageNo() int32 {
	if m != nil {
		return m.CurrentPageNo
	}
	return 0
}

func (m *Book) GetMaxNumPages() int32 {
	if m != nil {
		return m.MaxNumPages
	}
	return 0
}

func (m *Book) GetLastUpdatedTime() int64 {
	if m != nil {
		return m.LastUpdatedTime
	}
	return 0
}

func (m *Book) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *Book) GetEpubCreated() bool {
	if m != nil {
		return m.EpubCreated
	}
	return false
}

type BookList struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookList) Reset()         { *m = BookList{} }
func (m *BookList) String() string { return proto.CompactTextString(m) }
func (*BookList) ProtoMessage()    {}
func (*BookList) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_e737636721060213, []int{3}
}
func (m *BookList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookList.Unmarshal(m, b)
}
func (m *BookList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookList.Marshal(b, m, deterministic)
}
func (dst *BookList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookList.Merge(dst, src)
}
func (m *BookList) XXX_Size() int {
	return xxx_messageInfo_BookList.Size(m)
}
func (m *BookList) XXX_DiscardUnknown() {
	xxx_messageInfo_BookList.DiscardUnknown(m)
}

var xxx_messageInfo_BookList proto.InternalMessageInfo

func (m *BookList) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type NewBookRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartPageUrl         string   `protobuf:"bytes,2,opt,name=startPageUrl,proto3" json:"startPageUrl,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	MaxNumPages          int32    `protobuf:"varint,4,opt,name=maxNumPages,proto3" json:"maxNumPages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBookRequest) Reset()         { *m = NewBookRequest{} }
func (m *NewBookRequest) String() string { return proto.CompactTextString(m) }
func (*NewBookRequest) ProtoMessage()    {}
func (*NewBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_e737636721060213, []int{4}
}
func (m *NewBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBookRequest.Unmarshal(m, b)
}
func (m *NewBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBookRequest.Marshal(b, m, deterministic)
}
func (dst *NewBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBookRequest.Merge(dst, src)
}
func (m *NewBookRequest) XXX_Size() int {
	return xxx_messageInfo_NewBookRequest.Size(m)
}
func (m *NewBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewBookRequest proto.InternalMessageInfo

func (m *NewBookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewBookRequest) GetStartPageUrl() string {
	if m != nil {
		return m.StartPageUrl
	}
	return ""
}

func (m *NewBookRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *NewBookRequest) GetMaxNumPages() int32 {
	if m != nil {
		return m.MaxNumPages
	}
	return 0
}

type BookID struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookID) Reset()         { *m = BookID{} }
func (m *BookID) String() string { return proto.CompactTextString(m) }
func (*BookID) ProtoMessage()    {}
func (*BookID) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_e737636721060213, []int{5}
}
func (m *BookID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookID.Unmarshal(m, b)
}
func (m *BookID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookID.Marshal(b, m, deterministic)
}
func (dst *BookID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookID.Merge(dst, src)
}
func (m *BookID) XXX_Size() int {
	return xxx_messageInfo_BookID.Size(m)
}
func (m *BookID) XXX_DiscardUnknown() {
	xxx_messageInfo_BookID.DiscardUnknown(m)
}

var xxx_messageInfo_BookID proto.InternalMessageInfo

func (m *BookID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Chapter struct {
	ChapterNo            int32    `protobuf:"varint,1,opt,name=chapterNo,proto3" json:"chapterNo,omitempty"`
	BookId               int32    `protobuf:"varint,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Html                 []byte   `protobuf:"bytes,4,opt,name=html,proto3" json:"html,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chapter) Reset()         { *m = Chapter{} }
func (m *Chapter) String() string { return proto.CompactTextString(m) }
func (*Chapter) ProtoMessage()    {}
func (*Chapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_tusach_model_e737636721060213, []int{6}
}
func (m *Chapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chapter.Unmarshal(m, b)
}
func (m *Chapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chapter.Marshal(b, m, deterministic)
}
func (dst *Chapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chapter.Merge(dst, src)
}
func (m *Chapter) XXX_Size() int {
	return xxx_messageInfo_Chapter.Size(m)
}
func (m *Chapter) XXX_DiscardUnknown() {
	xxx_messageInfo_Chapter.DiscardUnknown(m)
}

var xxx_messageInfo_Chapter proto.InternalMessageInfo

func (m *Chapter) GetChapterNo() int32 {
	if m != nil {
		return m.ChapterNo
	}
	return 0
}

func (m *Chapter) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Chapter) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Chapter) GetHtml() []byte {
	if m != nil {
		return m.Html
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "model.User")
	proto.RegisterType((*SystemInfo)(nil), "model.SystemInfo")
	proto.RegisterType((*Book)(nil), "model.Book")
	proto.RegisterType((*BookList)(nil), "model.BookList")
	proto.RegisterType((*NewBookRequest)(nil), "model.NewBookRequest")
	proto.RegisterType((*BookID)(nil), "model.BookID")
	proto.RegisterType((*Chapter)(nil), "model.Chapter")
	proto.RegisterEnum("model.BookStatusType", BookStatusType_name, BookStatusType_value)
}

func init() { proto.RegisterFile("tusach_model.proto", fileDescriptor_tusach_model_e737636721060213) }

var fileDescriptor_tusach_model_e737636721060213 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x5f, 0x6b, 0xdb, 0x3c,
	0x14, 0xc6, 0x5f, 0xff, 0x4b, 0xe3, 0xe3, 0xd6, 0x0d, 0x7a, 0xb7, 0x21, 0xc6, 0x2e, 0x32, 0x33,
	0x46, 0x18, 0xb4, 0x94, 0xee, 0x13, 0xac, 0x6d, 0x18, 0x81, 0xd6, 0x09, 0x4a, 0x72, 0x5d, 0x9c,
	0x58, 0x6b, 0x4c, 0xed, 0xc8, 0x93, 0x64, 0xb6, 0xdc, 0xef, 0x1b, 0xee, 0x0b, 0x0d, 0x1d, 0x9b,
	0xc4, 0xf1, 0xba, 0x3b, 0x3d, 0x3f, 0x3d, 0xb2, 0xce, 0x39, 0x8f, 0x30, 0x10, 0x5d, 0xa9, 0x64,
	0xbd, 0x79, 0x2c, 0x44, 0xca, 0xf3, 0xcb, 0x52, 0x0a, 0x2d, 0x88, 0x87, 0x22, 0xba, 0x02, 0x77,
	0xa9, 0xb8, 0x24, 0x04, 0xdc, 0x6d, 0x52, 0x70, 0x6a, 0x0d, 0xad, 0x91, 0xcf, 0x70, 0x4d, 0x5e,
	0x81, 0x27, 0x45, 0xce, 0x15, 0xb5, 0x87, 0xce, 0xc8, 0x67, 0xb5, 0x88, 0x56, 0x00, 0xf3, 0x9d,
	0xd2, 0xbc, 0x98, 0x6c, 0xbf, 0x09, 0x12, 0xc1, 0xa9, 0x42, 0xb5, 0x2c, 0x17, 0x59, 0x73, 0xde,
	0x61, 0x47, 0x8c, 0x5c, 0xc1, 0xff, 0x2b, 0x21, 0x9e, 0xef, 0x13, 0xa5, 0x97, 0x65, 0x9a, 0x68,
	0x9e, 0xa2, 0xd5, 0x46, 0xeb, 0x4b, 0x5b, 0xd1, 0x6f, 0x07, 0xdc, 0x1b, 0x21, 0x9e, 0x49, 0x08,
	0x76, 0x96, 0xe2, 0x47, 0x3d, 0x66, 0x67, 0x29, 0xb9, 0x80, 0x9e, 0xd2, 0x89, 0xae, 0x14, 0x9e,
	0x0e, 0xaf, 0x5f, 0x5f, 0xd6, 0x3d, 0x19, 0xf3, 0x1c, 0x37, 0x16, 0xbb, 0x92, 0xb3, 0xc6, 0x64,
	0x3a, 0xd0, 0x99, 0xce, 0x39, 0x75, 0xb0, 0xad, 0x5a, 0x90, 0x37, 0xd0, 0x4b, 0x2a, 0xbd, 0x11,
	0x92, 0xba, 0x88, 0x1b, 0x45, 0x86, 0x10, 0xac, 0x25, 0xdf, 0xd7, 0xe7, 0x61, 0x7d, 0x6d, 0x44,
	0xde, 0x81, 0xdf, 0xc8, 0x9b, 0x1d, 0xed, 0xe1, 0xe1, 0x03, 0x30, 0xb3, 0x58, 0x55, 0x59, 0x8e,
	0xd6, 0x39, 0x5f, 0xd3, 0x13, 0x2c, 0xfb, 0x88, 0xe1, 0xbc, 0x74, 0x22, 0xf5, 0x2c, 0x79, 0xe2,
	0x4b, 0x99, 0xd3, 0x3e, 0x7e, 0xe4, 0x88, 0x91, 0x8f, 0x10, 0xae, 0x2b, 0x29, 0xf9, 0x76, 0xef,
	0xf2, 0xd1, 0xd5, 0xa1, 0xe4, 0x03, 0x9c, 0xb5, 0x48, 0x2c, 0x28, 0xe0, 0x85, 0xc7, 0xd0, 0x74,
	0x55, 0x24, 0x3f, 0xe3, 0xaa, 0x30, 0x5a, 0xd1, 0x00, 0x3d, 0x6d, 0x44, 0x46, 0x70, 0x9e, 0x77,
	0xb2, 0x39, 0xc5, 0xde, 0xbb, 0x98, 0xbc, 0x85, 0x3e, 0x97, 0x52, 0xc8, 0x07, 0xf5, 0x44, 0xcf,
	0xb0, 0xa6, 0xbd, 0x36, 0xf7, 0xf0, 0xb2, 0x5a, 0xdd, 0xd6, 0xe3, 0xa0, 0xe1, 0xd0, 0x1a, 0xf5,
	0x59, 0x1b, 0x45, 0x17, 0xd0, 0x37, 0x39, 0xdd, 0x67, 0x4a, 0x93, 0xf7, 0xe0, 0x99, 0xe0, 0x15,
	0xb5, 0x86, 0xce, 0x28, 0xb8, 0x0e, 0x5a, 0x39, 0xb2, 0x7a, 0x27, 0xfa, 0x65, 0x41, 0x18, 0xf3,
	0x1f, 0x88, 0xf8, 0xf7, 0x8a, 0x2b, 0x7d, 0xc8, 0xd3, 0x6a, 0xe7, 0xd9, 0x9d, 0xa9, 0xfd, 0xc2,
	0x4c, 0x0f, 0x99, 0x3b, 0xdd, 0xcc, 0xdb, 0xd3, 0x71, 0xff, 0x9a, 0x4e, 0x44, 0xa1, 0x67, 0x4a,
	0x98, 0xdc, 0x75, 0x1f, 0x63, 0x94, 0xc1, 0xc9, 0xed, 0x26, 0x29, 0x35, 0x97, 0xf8, 0x30, 0xea,
	0x65, 0x2c, 0x1a, 0xc7, 0x01, 0x98, 0xcb, 0x4d, 0x4b, 0x93, 0x14, 0x4b, 0xf3, 0x58, 0xa3, 0xfe,
	0xf1, 0x3c, 0x09, 0xb8, 0x1b, 0x5d, 0xe4, 0x58, 0xcb, 0x29, 0xc3, 0xf5, 0x27, 0x06, 0xe1, 0xf1,
	0x13, 0x27, 0x7d, 0x70, 0xe3, 0x69, 0x3c, 0x1e, 0xfc, 0x47, 0xce, 0x21, 0x98, 0xc4, 0x8f, 0x33,
	0x36, 0xfd, 0xca, 0xc6, 0xf3, 0xf9, 0xc0, 0x22, 0x67, 0xe0, 0xdf, 0x4e, 0x1f, 0x66, 0xf7, 0xe3,
	0xc5, 0xf8, 0x6e, 0x60, 0x13, 0x1f, 0xbc, 0x31, 0x63, 0x53, 0x36, 0x70, 0x48, 0x00, 0x27, 0x5f,
	0x6e, 0xa6, 0xcc, 0x70, 0x77, 0xd5, 0xc3, 0x1f, 0xc1, 0xe7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x63, 0xd9, 0xae, 0x6a, 0x1e, 0x04, 0x00, 0x00,
}
